### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by damp11113** [nejason57mars/mcbot#10]

**Comment by damp11113** [comment]
java.lang.NumberFormatException: For input string: "tcp"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at java.base/java.lang.Integer.parseInt(Integer.java:784)
        at xyz.mcbot.Main.main(Main.java:116)
